### ISSUE TITLE
Class of `invented_wages`

### ISSUE THREAD

**Issue by lionel-** [gibonet/distrr#1]
I'm seeing this failure with dplyr 1.0 and the dev version of vctrs:

```
checking examples ... ERROR

...
> str(invented_wages)
tibble [1,000 × 5] (S3: tbl_df/data.frame)
 $ gender        : Factor w/ 2 levels "men","women": 1 2 1 2 1 1 1 2 2 2 ...
 $ sector        : Factor w/ 2 levels "secondary","tertiary": 2 1 2 2 1 1 2 1 2 1 ...
 $ education     : Factor w/ 3 levels "I","II","III": 3 2 2 2 2 1 3 1 2 2 ...
 $ wage          : num [1:1000] 8400 4200 5100 7400 4300 4900 5400 2900 4500 3000 ...
 $ sample_weights: num [1:1000] 105 32 36 12 21 46 79 113 34 32 ...
> tmp <- dcc(.data = invented_wages, 
+            .variables = c("gender", "sector"), .fun = jointfun_)
Error: `vec_ptype2.tbl_df.tbl_df()` is implemented at C level.
This R function is purely indicative and should never be called.
Backtrace:
    █
 1. ├─distrr::dcc(...)
 2. │ └─distrr::dcc5(...)
 3. │   └─distrr:::prepare_data(...)
 4. │     └─dplyr::bind_cols(data_vars, data_others)
 5. │       └─vctrs::vec_cbind(!!!dots)
 6. └─vctrs:::vec_ptype2.tbl_df.tbl_df(...)
 7.   └─vctrs:::stop_native_implementation("vec_ptype2.tbl_df.tbl_df")
Execution halted
```

This is because the data frame you export does not have the proper class vector:

```r
class(invented_wages)
#> [1] "tbl_df"     "data.frame"
```

Perhaps you constructed it manually? If so, please use the `tibble::new_tibble()` constructor instead.

**Comment by gibonet** [comment]
I installed dplyr 1.0.0 and dev version of vctrs. I recreated the "invented_wages" tibble with tibble::new_tibble() as you suggested and now invented_wages has class "tbl_df" "tbl" "data.frame".

I did the check of the package and I get 0 errors ✓ | 0 warnings ✓ | 0 notes ✓

Is it ok for you?

**Comment by lionel-** [comment]
yes perfect, but note that `new_tibble()` is not a new functionality, so any version of tibble should do it.

**Comment by lionel-** [comment]
(I have patched up vctrs to work around this error, but it's still a good idea to use the constructor. Manipulating attributes of foreign classes is undefined behaviour.)

**Comment by gibonet** [comment]
Perfect. Thanks.
